
spring:
  datasource:
    dbcp2:
      url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/${MYSQL_DATABASE:shuwashuwa}?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:123456}
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8848

mybatis:
  type-aliases-package: team.combinatorics.shuwashuwa.model.pojo
  mapper-locations: classpath:\:mapper/*.xml

