version: '3.7'

x-restart-policy: &default-restart-policy
    restart: unless-stopped

x-logging: &default-logging
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
            max-file: "10"

x-env-file: &default-env-file
    env_file:
        - .env
        - .secrets.env

x-environment: &default-environment
    ADMIN_SECRET: ""
    DEV_SECRET: ""
    WX_APPID: ""
    WX_SECRET: ""

services: 
    nginx:
        image: nginx:1.25-alpine
        volumes:
            - ${NGINX_WWW}:/usr/share/nginx/html
            - ${NGINX_MEDIA}:/usr/share/nginx/media
            - ${NGINX_CONF}:/etc/nginx/templates/default.conf.template
        ports:
            - "${PORT}:80"
        <<: *default-logging
        <<: *default-restart-policy
        <<: *default-env-file
        environment:
            WX_APPID: ""
            WX_SECRET: ""
            MYSQL_PASSWORD: ""
            MYSQL_USER: ""

    adminer:
        image: adminer:4.8.1
        depends_on: 
            - mysql
        <<: *default-logging
        <<: *default-restart-policy
        <<: *default-env-file
        environment:
            <<: *default-environment

    dufs:
        image: sigoden/dufs:v0.36.0
        volumes:
            - ${NGINX_MEDIA}:/media
        command: /media -A --path-prefix ${NGINX_ADMIN_PREFIX}media
        <<: *default-logging
        <<: *default-restart-policy

    mysql:
        image: mysql:8.0.22
        volumes:
            - ${DBINIT}:/docker-entrypoint-initdb.d
            - ${DBSTORE}:/var/lib/mysql
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        env_file:
            - .secrets.env
        <<: *default-logging
        <<: *default-restart-policy
        <<: *default-env-file
        environment:
            <<: *default-environment

    mysql-cron-backup:
        image: fradelg/mysql-cron-backup:1.13.1
        depends_on:
            - mysql
        volumes:
            - ${BACKUPSTORE}:/backup
        environment:
            <<: *default-environment
        <<: *default-logging
        <<: *default-restart-policy
        <<: *default-env-file

    shuwashuwa:
        build: 
            context: ../
            dockerfile: ./server-production/prod.dockerfile
        volumes:
            - ${TARGET_PATH}:/target/target.jar
            - ${PIC_PATH}:/pic
        environment: 
            PIC_PATH: /pic
            ADMIN_SECRET: ""
            DEV_SECRET: ""
        depends_on: 
            - mysql
        <<: *default-logging
        <<: *default-restart-policy
        <<: *default-env-file

